import { TYPE_CODES } from 'src/modules/core/types/constants/type-codes';

// Legacy string upload_type values used by the not-yet-rebuilt upload services, mapped to the
// canonical UPLOAD_TYPE core.types codes.
export const LEGACY_UPLOAD_TYPE_CODES: Record<string, string> = {
	DOCENTE: TYPE_CODES.UPLOAD_TYPE.STAFF,
	MALLA_CURRICULAR: TYPE_CODES.UPLOAD_TYPE.STUDY_PLAN,
	MALLA_COCOS: TYPE_CODES.UPLOAD_TYPE.OUTCOMES,
	ORGANIGRAMA: TYPE_CODES.UPLOAD_TYPE.ORGANIZATION_CHART,
	SECCION: TYPE_CODES.UPLOAD_TYPE.SECTIONS,
	ALUMNOS_MATRICULADOS: TYPE_CODES.UPLOAD_TYPE.ENROLLED_STUDENTS,
	NOTASRC: TYPE_CODES.UPLOAD_TYPE.RC_GRADES,
	ALUMNOS_POR_SECCION: TYPE_CODES.UPLOAD_TYPE.STUDENT_SECTION_ENROLLMENT,
};
