export const graValidationStrings = {
	error: {
		configNotFound: 'error.survey.gra.configNotFound',
		tokenNotFound: 'error.survey.gra.tokenNotFound',
		tokenExpired: 'error.survey.gra.tokenExpired',
		alreadyCompleted: 'error.survey.gra.alreadyCompleted',
		noScores: 'error.survey.gra.noScores',
		invalidScore: 'error.survey.gra.invalidScore',
		noPending: 'error.survey.gra.noPending',
		seedMissing: 'error.survey.gra.seedMissing',
		studentAlreadyNotified: 'error.survey.gra.studentAlreadyNotified',
		notificationNotFound: 'error.survey.gra.notificationNotFound',
		completeFailed: 'error.survey.gra.completeFailed',
		emailTemplateMissing: 'error.survey.gra.emailTemplateMissing',
		emailTemplateCategoryMissing: 'error.survey.gra.emailTemplateCategoryMissing',
		invalidExcelFile: 'error.survey.gra.invalidExcelFile',
		excelNoSheets: 'error.survey.gra.excelNoSheets',
		excelEmpty: 'error.survey.gra.excelEmpty',
		defaultCampusMissing: 'error.survey.gra.defaultCampusMissing',
		emptyStudentCode: 'error.survey.gra.emptyStudentCode',
		studentNotFound: 'error.survey.gra.studentNotFound',
		alreadyInList: 'error.survey.gra.alreadyInList',
		programRequired: 'error.survey.gra.programRequired',
	},
	success: {
		notificationCreated: 'success.survey.gra.notificationCreated',
		completed: 'success.survey.gra.completed',
	},
};
