export const evaluationsValidationStrings = {
	error: {
		evaluationExists: 'error.evaluation.evaluationExists',
		notFound: 'error.evaluation.notFound',
		evaluatorOrStudentNotFound: 'error.evaluation.evaluatorOrStudentNotFound',
		notSameProject: 'error.evaluation.notSameProject',
		projectNotFound: 'error.evaluation.projectNotFound',
		noRubricForProject: 'error.evaluation.noRubricForProject',
		rubricNotFound: 'error.evaluation.rubricNotFound',
		criteriaNotFound: 'error.evaluation.criteriaNotFound',
		invalidScore: 'error.evaluation.invalidScore',
		invalidScoreCapstone: 'error.evaluation.invalidScoreCapstone',
		allCriteriaRequired: 'error.evaluation.allCriteriaRequired',
		oneCriteriaPerQuestion: 'error.evaluation.oneCriteriaPerQuestion',
		statusTypeNotFound: 'error.evaluation.statusTypeNotFound',
		docCannotGrade: 'error.evaluation.docCannotGrade',
		inactiveEvaluatorCannotGrade: 'error.evaluation.inactiveEvaluatorCannotGrade',
		onlyComiteCanGrade: 'error.evaluation.onlyComiteCanGrade',
		gradeAllStudents: 'error.evaluation.gradeAllStudents',
		observationRequired: 'error.evaluation.observationRequired',
	},
	result: {
		createFailed: 'error.evaluation.createFailed',
		updateFailed: 'error.evaluation.updateFailed',
		deleteFailed: 'error.evaluation.deleteFailed',
		submitted: 'success.evaluation.submitted',
		saved: 'success.evaluation.saved',
		finalized: 'success.evaluation.finalized',
	},
};
