export const portfolioValidationStrings = {
	error: {
		companyRequired: 'error.portfolio.companyRequired',
		projectNotFound: 'error.portfolio.projectNotFound',
		studentOneNotFound: 'error.portfolio.studentOneNotFound',
		studentTwoNotFound: 'error.portfolio.studentTwoNotFound',
		coauthorNotFound: 'error.portfolio.coauthorNotFound',
		consultantNotFound: 'error.portfolio.consultantNotFound',
		hasApplications: 'error.portfolio.hasApplications',
		studentNotAssigned: 'error.portfolio.studentNotAssigned',
		applicationExists: 'error.portfolio.applicationExists',
		periodNotFound: 'error.portfolio.periodNotFound',
		noPeriodForModality: 'error.portfolio.noPeriodForModality',
		companyNotFoundByCode: 'error.portfolio.companyNotFoundByCode',
		companyNotFoundById: 'error.portfolio.companyNotFoundById',
		programNotFound: 'error.portfolio.programNotFound',
	},
	result: {
		createFailed: 'error.portfolio.createFailed',
		updateFailed: 'error.portfolio.updateFailed',
		deleteFailed: 'error.portfolio.deleteFailed',
		deleteSucceeded: 'result.portfolio.deleteSucceeded',
		projectAutoDeleted: 'result.portfolio.projectAutoDeleted',
	},
};
