export const ifcsValidationStrings = {
	error: {
		ifcExists: 'error.ifc.exists',
		notFound: 'error.notFound',
		invalidTransition: 'error.ifc.invalidTransition',
		staffRequired: 'error.ifc.staffRequired',
		ownCoordinatorForbidden: 'error.ifc.ownCoordinatorForbidden',
		notInChain: 'error.ifc.notInChain',
		chartNotFound: 'error.ifc.chartNotFound',
		alreadyExists: 'error.ifc.alreadyExists',
		notEditable: 'error.ifc.notEditable',
		findingTempIdMissing: 'error.ifc.findingTempIdMissing',
		ifcInstrumentMissing: 'error.ifc.ifcInstrumentMissing',
	},
	result: {
		createFailed: 'error.ifc.createFailed',
		updateFailed: 'error.update.failed',
		deleteFailed: 'error.delete.failed',
		viewFailed: 'error.ifc.viewFailed',
		submitFailed: 'error.ifc.submitFailed',
		approveFailed: 'error.ifc.approveFailed',
		rejectFailed: 'error.ifc.rejectFailed',
		patchFailed: 'error.ifc.patchFailed',
		prefillFailed: 'error.ifc.prefillFailed',
	},
};
