export const ifcsValidationStrings = {
	error: {
		ifcExists: 'error.ifc.ifcExists',
		notFound: 'error.ifc.notFound',
		invalidTransition: 'error.ifc.invalidTransition',
		staffRequired: 'error.ifc.staffRequired',
		notInChain: 'error.ifc.notInChain',
		higherLevelRequired: 'error.ifc.higherLevelRequired',
		chartNotFound: 'error.ifc.chartNotFound',
		alreadyExists: 'error.ifc.alreadyExists',
		notEditable: 'error.ifc.notEditable',
		findingTempIdMissing: 'error.ifc.findingTempIdMissing',
		ifcInstrumentMissing: 'error.ifc.ifcInstrumentMissing',
		pdfRequiresApproved: 'error.ifc.pdfRequiresApproved',
		findingsRequired: 'error.ifc.findingsRequired',
		actionsRequiredPerFinding: 'error.ifc.actionsRequiredPerFinding',
		previousActionNotEligible: 'error.ifc.previousActionNotEligible',
	},
	result: {
		createFailed: 'error.ifc.createFailed',
		updateFailed: 'error.ifc.updateFailed',
		deleteFailed: 'error.ifc.deleteFailed',
		viewFailed: 'error.ifc.viewFailed',
		submitFailed: 'error.ifc.submitFailed',
		approveFailed: 'error.ifc.approveFailed',
		rejectFailed: 'error.ifc.rejectFailed',
		patchFailed: 'error.ifc.patchFailed',
		prefillFailed: 'error.ifc.prefillFailed',
		pdfFailed: 'error.ifc.pdfFailed',
		pdfBulkFailed: 'error.ifc.pdfBulkFailed',
		statusReportFailed: 'error.ifc.statusReportFailed',
	},
};
