export const gradesRvTemplateLabels: Record<string, Record<string, string>> = {
	es: {
		escuelaCode: 'Código de escuela',
		carreraCode: 'Código de carrera',
		commissionCode: 'Código de comisión',
		courseCode: 'Código de curso',
		studentCode: 'Código del alumno',
		sectionCode: 'Código de sección',
		professorCode: 'Código del docente',
		gradeTypeCode: 'Código de tipo de nota',
		projectCode: 'Código del proyecto',
		projectNameEs: 'Nombre del proyecto (ES)',
		projectNameEn: 'Nombre del proyecto (EN)',
		projectDescEs: 'Descripción del proyecto (ES)',
		projectDescEn: 'Descripción del proyecto (EN)',
		errorColumn: 'Mensaje de error',
		errorsFileName: 'ErroresCargaNotasRV.xlsx',
		templateFileName: 'PlantillaNotasRV.xlsx',
		instructionsTitle: 'Instrucciones de llenado',
		instructionsColField: 'Campo',
		instructionsColDescription: 'Descripción',
		instructionsColRequired: 'Obligatorio',
		instructionsColExample: 'Ejemplo',
		instructionsYes: 'Sí',
		instructionsNo: 'No',
		gradeTypesTitle: 'Tipos de nota disponibles',
		gradeTypesColCode: 'Código',
		gradeTypesColName: 'Nombre',
	},
	en: {
		escuelaCode: 'School code',
		carreraCode: 'Program code',
		commissionCode: 'Commission code',
		courseCode: 'Course code',
		studentCode: 'Student code',
		sectionCode: 'Section code',
		professorCode: 'Professor code',
		gradeTypeCode: 'Grade type code',
		projectCode: 'Project code',
		projectNameEs: 'Project name (ES)',
		projectNameEn: 'Project name (EN)',
		projectDescEs: 'Project description (ES)',
		projectDescEn: 'Project description (EN)',
		errorColumn: 'Error message',
		errorsFileName: 'GradesRvUploadErrors.xlsx',
		templateFileName: 'GradesRvTemplate.xlsx',
		instructionsTitle: 'Fill instructions',
		instructionsColField: 'Field',
		instructionsColDescription: 'Description',
		instructionsColRequired: 'Required',
		instructionsColExample: 'Example',
		instructionsYes: 'Yes',
		instructionsNo: 'No',
		gradeTypesTitle: 'Available grade types',
		gradeTypesColCode: 'Code',
		gradeTypesColName: 'Name',
	},
};

export const gradesRvErrorMessages: Record<string, Record<string, string>> = {
	es: {
		duplicateRowInFile: 'Fila duplicada en el archivo (sección y alumno repetidos).',
		escuelaCodeEmpty: 'El código de escuela es obligatorio.',
		escuelaNotFound: 'No existe una escuela con ese código.',
		carreraCodeEmpty: 'El código de carrera es obligatorio.',
		carreraNotFound: 'No existe una carrera con ese código.',
		carreraNotInEscuela: 'La carrera no pertenece a la escuela indicada.',
		commissionCodeEmpty: 'El código de comisión es obligatorio.',
		commissionNotFound: 'No existe una comisión habilitada con ese código para este período.',
		courseCodeEmpty: 'El código de curso es obligatorio.',
		courseNotFound: 'No existe un curso evaluable con ese código para este período.',
		sectionCodeEmpty: 'El código de sección es obligatorio.',
		sectionNotFound: 'No existe una sección con ese código para el curso y período indicados.',
		studentCodeEmpty: 'El código del alumno es obligatorio.',
		studentNotFound: 'No existe un alumno con ese código.',
		enrollmentNotFound: 'El alumno no está matriculado activamente en esa sección.',
		studentAlreadyInProject: 'El alumno ya tiene un proyecto académico en este período.',
		professorCodeEmpty: 'El código del docente es obligatorio.',
		professorNotFound: 'No existe un docente con ese código.',
		gradeTypeCodeEmpty: 'El tipo de evaluación es obligatorio.',
		gradeTypeNotFound: 'El tipo de evaluación no es válido.',
		noGradesProvided: 'Debe ingresar al menos una nota (O1–O7).',
		gradeInvalid: 'Una o más notas no son números válidos.',
		gradeOutOfRange: 'Una o más notas están fuera del rango permitido (0–2).',
		noOutcomesMapped:
			'El curso no tiene outcomes de verificación mapeados para la comisión indicada.',
		projectCodeEmpty: 'El código de proyecto es obligatorio.',
		projectCodeDuplicate: 'Ya existe un proyecto con ese código.',
		projectNameEmpty: 'El nombre del proyecto (ES) es obligatorio.',
	},
	en: {
		duplicateRowInFile: 'Duplicate row in the file (section and student repeated).',
		escuelaCodeEmpty: 'School code is required.',
		escuelaNotFound: 'No school exists with that code.',
		carreraCodeEmpty: 'Program code is required.',
		carreraNotFound: 'No program exists with that code.',
		carreraNotInEscuela: 'The program does not belong to the indicated school.',
		commissionCodeEmpty: 'Commission code is required.',
		commissionNotFound: 'No active commission exists with that code for this period.',
		courseCodeEmpty: 'Course code is required.',
		courseNotFound: 'No evaluable course exists with that code for this period.',
		sectionCodeEmpty: 'Section code is required.',
		sectionNotFound: 'No section exists with that code for the given course and period.',
		studentCodeEmpty: 'Student code is required.',
		studentNotFound: 'No student exists with that code.',
		enrollmentNotFound: 'The student is not actively enrolled in that section.',
		studentAlreadyInProject: 'The student already has an academic project in this period.',
		professorCodeEmpty: 'Professor code is required.',
		professorNotFound: 'No professor exists with that code.',
		gradeTypeCodeEmpty: 'Grade type is required.',
		gradeTypeNotFound: 'The grade type is not valid.',
		noGradesProvided: 'At least one grade (O1–O7) must be provided.',
		gradeInvalid: 'One or more grades are not valid numbers.',
		gradeOutOfRange: 'One or more grades are outside the allowed range (0–2).',
		noOutcomesMapped:
			'The course has no verification outcomes mapped for the indicated commission.',
		projectCodeEmpty: 'Project code is required.',
		projectCodeDuplicate: 'A project with that code already exists.',
		projectNameEmpty: 'Project name (ES) is required.',
	},
};

export const DEFAULT_TEMPLATE_LANGUAGE = 'es';

export interface FieldInstruction {
	field: string;
	description: string;
	required: boolean;
	example: string;
}

export const gradesRvFieldInstructions: Record<string, FieldInstruction[]> = {
	es: [
		{
			field: 'Código de escuela',
			description: 'Código de la escuela a la que pertenece la carrera.',
			required: true,
			example: 'ESCI',
		},
		{
			field: 'Código de carrera',
			description: 'Código de la carrera del alumno. Debe pertenecer a la escuela indicada.',
			required: true,
			example: 'ING-SISTEMAS',
		},
		{
			field: 'Código de comisión',
			description: 'Código de la comisión ABET habilitada para el período académico.',
			required: true,
			example: 'COM-2024-01',
		},
		{
			field: 'Código de curso',
			description: 'Código del curso a evaluar.',
			required: true,
			example: 'CS-401',
		},
		{
			field: 'Código del alumno',
			description:
				'Código del alumno. Si el mismo alumno aparece en más de una fila, la última fila sobreescribe todo lo anterior.',
			required: true,
			example: '20201234567',
		},
		{
			field: 'Código de sección',
			description: 'Código de la sección en la que está matriculado el alumno.',
			required: true,
			example: 'CS401-S1',
		},
		{
			field: 'Código del docente',
			description: 'Código del docente evaluador (se registra como tipo Comité).',
			required: true,
			example: 'N12345678',
		},
		{
			field: 'Código de tipo de nota',
			description: 'Código del tipo de evaluación. Debe existir en el grupo de tipos TG205.',
			required: true,
			example: 'TG205-T001',
		},
		{
			field: 'O1 – O7',
			description:
				'Nota por outcome de verificación (O1 = primer outcome ordenado por código ASC, O2 = segundo, etc.). Rango permitido: 0 a 2. Se puede dejar en blanco si el outcome no aplica para ese alumno.',
			required: false,
			example: '2',
		},
		{
			field: 'Código del proyecto',
			description:
				'Código único del proyecto académico. Si varios alumnos comparten el mismo código, quedan vinculados al mismo proyecto. Debe ser único en todo el sistema.',
			required: true,
			example: 'PROY-2024-001',
		},
		{
			field: 'Nombre del proyecto (ES)',
			description: 'Nombre del proyecto en español.',
			required: true,
			example: 'Sistema de gestión académica',
		},
		{
			field: 'Nombre del proyecto (EN)',
			description: 'Nombre del proyecto en inglés. Si se deja en blanco, se usará "-".',
			required: false,
			example: 'Academic management system',
		},
		{
			field: 'Descripción del proyecto (ES)',
			description: 'Descripción del proyecto en español. Opcional.',
			required: false,
			example: 'Sistema web para gestión de notas y asistencia.',
		},
		{
			field: 'Descripción del proyecto (EN)',
			description: 'Descripción del proyecto en inglés. Opcional.',
			required: false,
			example: 'Web system for grade and attendance management.',
		},
	],
	en: [
		{
			field: 'School code',
			description: 'Code of the school the program belongs to.',
			required: true,
			example: 'ESCI',
		},
		{
			field: 'Program code',
			description: "Code of the student's program. Must belong to the indicated school.",
			required: true,
			example: 'CS-ENG',
		},
		{
			field: 'Commission code',
			description: 'Code of the ABET commission enabled for the academic period.',
			required: true,
			example: 'COM-2024-01',
		},
		{
			field: 'Course code',
			description: 'Code of the course being evaluated.',
			required: true,
			example: 'CS-401',
		},
		{
			field: 'Student code',
			description:
				'Student code. If the same student appears in more than one row, the last row overwrites everything.',
			required: true,
			example: '20201234567',
		},
		{
			field: 'Section code',
			description: 'Code of the section in which the student is enrolled.',
			required: true,
			example: 'CS401-S1',
		},
		{
			field: 'Professor code',
			description: 'Code of the evaluating professor (registered as Committee type).',
			required: true,
			example: 'N12345678',
		},
		{
			field: 'Grade type code',
			description: 'Code of the evaluation type. Must exist in type group TG205.',
			required: true,
			example: 'TG205-T001',
		},
		{
			field: 'O1 – O7',
			description:
				'Grade per verification outcome (O1 = first outcome ordered by code ASC, O2 = second, etc.). Allowed range: 0 to 2. May be left blank if the outcome does not apply to the student.',
			required: false,
			example: '2',
		},
		{
			field: 'Project code',
			description:
				'Unique project code. If multiple students share the same code, they are linked to the same project. Must be unique system-wide.',
			required: true,
			example: 'PROJ-2024-001',
		},
		{
			field: 'Project name (ES)',
			description: 'Project name in Spanish.',
			required: true,
			example: 'Academic management system',
		},
		{
			field: 'Project name (EN)',
			description: 'Project name in English. If left blank, "-" will be used.',
			required: false,
			example: 'Academic management system',
		},
		{
			field: 'Project description (ES)',
			description: 'Project description in Spanish. Optional.',
			required: false,
			example: 'Web system for grade and attendance management.',
		},
		{
			field: 'Project description (EN)',
			description: 'Project description in English. Optional.',
			required: false,
			example: 'Web system for grade and attendance management.',
		},
	],
};
