export const PARAMETER_CODES = {
	LANGUAGES: 'PARAMETER_LANGUAGES',
	FINDING_PREFIX: 'PARAMETER_FINDING_PREFIX',
	ACTION_PREFIX: 'PARAMETER_ACTION_PREFIX',
	IFC_FIELDS: 'PARAMETER_IFC_FIELDS',
} as const;

// Fallback when PARAMETER_LANGUAGES is not configured.
export const DEFAULT_LANGUAGES = ['es', 'en'];
